### ISSUE TITLE
stream_of_byte->complete() should no longer emit next/error events

### ISSUE THREAD

**Issue by artfuldev** [artfuldev/libstream#4]
When a `stream->complete()` is called, the `stream->next(v)` and `stream->error(e)` should no longer work.

**Comment by artfuldev** [comment]
should we replace them with a noop function?

**Comment by artfuldev** [comment]
@navaneeth will freeing the varray by calling `varray_free(stream->listeners)` destroy the listener streams from memory? or just the pointers to those listeners will get removed?

**Comment by artfuldev** [comment]
Moved to https://github.com/artfuldev/RIoT/issues/2

**Comment by navaneeth** [comment]
@artfuldev `varray_free` won't clean the data. It just cleans the array. You will have to pass a destructor function. See here - https://github.com/varnamproject/libvarnam/blob/master/varray.h#L70
